# Generated by Django 5.2.5 on 2025-08-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "price_type",
                    models.CharField(
                        choices=[("paid", "유료"), ("free", "무료"), ("negotiable", "협의")],
                        default="negotiable",
                        max_length=20,
                    ),
                ),
                ("price_amount", models.IntegerField(blank=True, null=True)),
                ("region", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="categories.category"),
                ),
            ],
        ),
    ]
