# Generated by Django 5.0.6 on 2025-09-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("postings", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posting",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="spaces.space",
            ),
        ),
    ]
