# Generated by Django 5.2.6 on 2025-09-22 14:26

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="posting_image",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="postings/",
            ),
        ),
        migrations.AlterField(
            model_name="posting",
            name="posting_image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
