# Generated by Django 5.2.5 on 2025-08-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kakao_id", models.CharField(max_length=255, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("artist", "Artist"), ("space", "Space")],
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
