# Generated by Django 5.2.5 on 2025-08-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("artist", "Artist"), ("space", "Space")], max_length=10
            ),
        ),
    ]
