# Generated by Django 5.2.6 on 2025-09-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kakao_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
