# Generated by Django 5.2.5 on 2025-08-29 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("artist", "Artist → Space"),
                            ("space", "Space → Artist"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("performance_date", models.DateField()),
                ("performance_time", models.DateTimeField(blank=True, null=True)),
                ("running_time_minutes", models.IntegerField(blank=True, null=True)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_performed_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_suggestions",
                        to="artists.artist",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_suggestions",
                        to="spaces.space",
                    ),
                ),
            ],
        ),
    ]
