# Generated by Django 5.2.5 on 2025-09-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_free_allowed_suggestion", models.BooleanField(default=False)),
                (
                    "is_performed_confirmed",
                    models.BooleanField(
                        default=False, help_text="공간 보유자만 공연 완료 여부를 체크할 수 있습니다."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "미확인"),
                            ("accepted", "수락"),
                            ("rejected", "거절"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_suggestions",
                        to="users.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_suggestions",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
