# Generated by Django 5.0.6 on 2025-09-05 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_type",
                    models.CharField(
                        choices=[
                            ("artist", "Artist → Space"),
                            ("space", "Space → Artist"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_free_allowed", models.BooleanField(default=False)),
                ("is_performed_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artist_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artists.artist"
                    ),
                ),
                (
                    "space_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="spaces.space"
                    ),
                ),
            ],
        ),
    ]
