# Generated by Django 5.2.6 on 2025-09-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_remove_artist_category_artist_categories_and_more"),
        ("spaces", "0003_spacecategory_remove_space_category_and_more"),
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions_as_artist",
                to="artists.artist",
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suggestions_as_space",
                to="spaces.space",
            ),
        ),
    ]
