# Generated by Django 5.2.5 on 2025-08-29 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestion",
            name="performance_time",
        ),
        migrations.RemoveField(
            model_name="suggestion",
            name="running_time_minutes",
        ),
    ]
