# Generated by Django 5.2.6 on 2025-09-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="suggestion",
            name="uniq_pending_suggestion_artist_space",
        ),
    ]
