# Generated by Django 5.2.6 on 2025-09-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0002_remove_suggestion_uniq_pending_suggestion_artist_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
