# Generated by Django 5.2.5 on 2025-09-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("place_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("kakao_map_link", models.URLField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("카페", "카페"),
                            ("소극장", "소극장"),
                            ("공공기관", "공공기관"),
                            ("기업", "기업"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity_seated", models.IntegerField(blank=True, null=True)),
                ("capacity_standing", models.IntegerField(blank=True, null=True)),
                ("is_planning_host", models.BooleanField(default=False)),
                (
                    "business_registration_number",
                    models.CharField(max_length=10, unique=True),
                ),
                ("atmosphere", models.JSONField(blank=True, default=list)),
                (
                    "place_region",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("place_image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preferred_categories",
                    models.ManyToManyField(blank=True, to="categories.category"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
