# Generated by Django 5.0.6 on 2025-09-05 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("place_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                ("kakao_map_link", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity_seated", models.IntegerField(blank=True, null=True)),
                ("capacity_standing", models.IntegerField(blank=True, null=True)),
                ("is_planning_host", models.BooleanField(default=False)),
                (
                    "business_registration_number",
                    models.CharField(max_length=10, unique=True),
                ),
                ("atmosphere", models.JSONField(blank=True, default=list)),
                (
                    "place_region",
                    models.CharField(
                        blank=True, editable=False, max_length=100, null=True
                    ),
                ),
                ("place_image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preferred_categories",
                    models.ManyToManyField(blank=True, to="categories.category"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spaces.spacecategory",
                    ),
                ),
            ],
        ),
    ]
