# Generated by Django 5.2.5 on 2025-09-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0002_spacecategory_alter_space_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="place_region",
            field=models.CharField(
                blank=True, editable=False, max_length=100, null=True
            ),
        ),
    ]
