# Generated by Django 5.2.6 on 2025-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpaceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="space",
            name="category",
        ),
        migrations.AlterField(
            model_name="space",
            name="place_image",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="space",
            name="place_image_url",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="space",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="spaces", to="spaces.spacecategory"
            ),
        ),
    ]
