# Generated by Django 5.2.6 on 2025-09-22 14:26

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0003_spacecategory_remove_space_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="place_image_list",
            field=models.JSONField(
                blank=True, default=list, help_text="Cloudinary public_id 목록"
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="place_image",
            field=models.ImageField(
                blank=True,
                max_length=10000,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="spaces/place/",
            ),
        ),
        migrations.AlterField(
            model_name="space",
            name="place_image_url",
            field=models.JSONField(
                blank=True, default=list, help_text="Cloudinary URL 목록"
            ),
        ),
    ]
