# Generated by Django 5.2.6 on 2025-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0004_space_place_image_list_alter_space_place_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="place_image_list",
        ),
        migrations.AlterField(
            model_name="space",
            name="place_image",
            field=models.JSONField(
                blank=True, default=list, help_text="Cloudinary public_id 목록"
            ),
        ),
    ]
