# Generated by Django 5.2.6 on 2025-09-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0005_remove_space_place_image_list_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="kakao_map_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
