# Generated by Django 5.2.6 on 2025-09-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0006_alter_space_kakao_map_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="place_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
