# Generated by Django 5.2.5 on 2025-09-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0001_initial"),
        ("likes", "0001_initial"),
        ("spaces", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="like",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="spaces.space",
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("user", "artist"), name="unique_user_artist_like"
            ),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("user", "space"), name="unique_user_space_like"
            ),
        ),
        migrations.RemoveField(
            model_name="like",
            name="target_name",
        ),
        migrations.RemoveField(
            model_name="like",
            name="target_type",
        ),
    ]
