# Generated by Django 5.0.6 on 2025-09-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("spaceequipments", "0001_initial"),
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spaceequipment",
            name="space",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="spaces.space",
            ),
        ),
    ]
