# Generated by Django 5.2.5 on 2025-08-29 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField(blank=True, null=True)),
                ("number_of_members", models.IntegerField(default=1)),
                (
                    "custom_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("portfolio_links", models.JSONField(blank=True, default=list)),
                ("profile_image_url", models.URLField(blank=True, null=True)),
                ("region", models.JSONField(blank=True, default=list)),
                ("desired_pay", models.IntegerField(blank=True, null=True)),
                ("is_free_allowed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
