# Generated by Django 5.2.5 on 2025-08-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("users", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("number_of_members", models.IntegerField(default=1)),
                ("portfolio_links", models.JSONField(blank=True, default=list)),
                ("profile_image_url", models.URLField(blank=True)),
                ("region", models.JSONField(blank=True, default=list)),
                ("desired_pay", models.IntegerField(blank=True, null=True)),
                ("is_free_allowed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
