# Generated by Django 5.2.6 on 2025-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="category",
        ),
        migrations.AddField(
            model_name="artist",
            name="categories",
            field=models.ManyToManyField(blank=True, to="categories.category"),
        ),
        migrations.AlterField(
            model_name="artist",
            name="profile_image",
            field=models.ImageField(
                blank=True, max_length=10000, null=True, upload_to="artists/profile/"
            ),
        ),
        migrations.AlterField(
            model_name="artist",
            name="profile_image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
