# Generated by Django 5.2.6 on 2025-09-22 14:26

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0003_remove_artist_category_artist_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=10000,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="artists/profile/",
            ),
        ),
    ]
