# Generated by Django 5.0.6 on 2025-09-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artistequipments", "0001_initial"),
        ("artists", "0001_initial"),
        ("equipmentcategories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistequipment",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="artistequipment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipmentcategories.equipmentcategory",
            ),
        ),
    ]
