# Generated by Django 5.2.5 on 2025-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="target_link",
            field=models.URLField(),
        ),
    ]
